package com.example.demo.dao;

import com.example.demo.dao.model.Kdgs;
import com.example.demo.dao.model.KdgsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KdgsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kdgs
     *
     * @mbg.generated Sat Mar 06 13:35:50 CST 2021
     */
    long countByExample(KdgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kdgs
     *
     * @mbg.generated Sat Mar 06 13:35:50 CST 2021
     */
    int deleteByExample(KdgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kdgs
     *
     * @mbg.generated Sat Mar 06 13:35:50 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kdgs
     *
     * @mbg.generated Sat Mar 06 13:35:50 CST 2021
     */
    int insert(Kdgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kdgs
     *
     * @mbg.generated Sat Mar 06 13:35:50 CST 2021
     */
    int insertSelective(Kdgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kdgs
     *
     * @mbg.generated Sat Mar 06 13:35:50 CST 2021
     */
    List<Kdgs> selectByExample(KdgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kdgs
     *
     * @mbg.generated Sat Mar 06 13:35:50 CST 2021
     */
    Kdgs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kdgs
     *
     * @mbg.generated Sat Mar 06 13:35:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") Kdgs record, @Param("example") KdgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kdgs
     *
     * @mbg.generated Sat Mar 06 13:35:50 CST 2021
     */
    int updateByExample(@Param("record") Kdgs record, @Param("example") KdgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kdgs
     *
     * @mbg.generated Sat Mar 06 13:35:50 CST 2021
     */
    int updateByPrimaryKeySelective(Kdgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kdgs
     *
     * @mbg.generated Sat Mar 06 13:35:50 CST 2021
     */
    int updateByPrimaryKey(Kdgs record);

    List<Kdgs> getAllKdgs();
}